
# 加解密根密码
jasypt:
  encryptor:
    password: pig #根密码

# Spring 相关
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  #采样率
  sleuth:
    sampler:
      probability: 0.5

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

# feign 配置
feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
  compression:
    request:
      enabled: true
    response:
      enabled: true

# hystrix 配置
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 55000
  shareSecurityContext: true

#请求处理的超时时间
ribbon:
  ReadTimeout: 50000
  ConnectTimeout: 50000
