spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://local.mysql.com:3306/zero_cloud?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1
  mvc:
    servlet:
      load-on-startup: 1
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    sender:
      type: web
zuul:
  ignored-services: '*'
  sensitiveHeaders: 
  routes:
    oauth:
      path: /api-o/**
      serviceId: oauth-server
    user:
      path: /api-u/**
      serviceId: user-server
    log:
      path: /api-l/**
      serviceId: log-server
    api-m:
      path: /api-m/**
      serviceId: monitor-server
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  add-proxy-headers: true
  ribbon:
    eager-load:
      enabled: true
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
cron:
  black-ip: 0 0/5 * * * ?